feat(data-bridge): Add new data bridge introduction and kafka/mysql/i…
wivwiv/emqx-docs pull request #1
Opened 2022-12-26 05:38 UTC by wivwiv

2022-12-26 06:27 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +## 数据桥接指标
数据桥接相关指标或者相关指标

2022-12-26 06:28 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +数据桥接提供了运行统计指标，包括：
您可通过以下指标查看数据桥接的运行统计：

2022-12-26 06:29 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +<!-- - 命中：
我感觉这些都是数据桥接的运行状态吧，我看这个章节的标题是指标，好像没有提到指标？

2022-12-26 06:31 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +## 数据桥接特性
直接叫“功能特性”？

2022-12-26 06:33 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +数据桥接借助以下特性以增强易用性、进一步提高数据集成的性能和可靠性，并非所有数据桥接都完全实现了这些特性，具体支持情况请参照各自的说明文档。
您可通过以下简单易用的数据桥接功能特性来进一步提高数据集成的性能和可靠性。注意：根据您选择的数据桥接方式，部分功能特性可能暂时不可用，具体支持情况请参照各自的说明文档。

另外“说明文档”这里要不要超链接一下？

2022-12-26 06:37 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +连接池是指一组可重复使用的连接对象，通过提高连接效率、避免每次请求重新创建连接，连接池可以减少资源消耗能够支持大量并发请求。
连接池是指一组可重复使用的连接对象。由于无需再为每次请求重新创建连接，连接池可以帮助减少资源消耗、提升连接效率、并可以支持较高的并发请求。

2022-12-26 06:42 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +EMQX 单个数据桥接在每个节点独立使用一个连接池，举个例子，当您使用 3 个 EMQX 节点集群并设置某个数据集成的连接池大小为 8，整个集群将建立 3x8 = 24 个连接，请留意您所用资源对连接数的限制。
EMQX 会为每个数据桥接所在的节点单独创建一个连接池，举个例子，假设您使用了 3 个 EMQX 节点、且每个数据桥接的连接池大小设为 8，那么 EMQX 将建立 3 x 8 = 24 个连接池。注意：请留意您所用资源对连接数的限制。

这里原文里的”数据桥接“、”连接“、”连接池“”连接“ 我觉得有点混乱，我修改了，麻烦确认下是不是这个意思。

2022-12-26 06:45 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +数据桥接数据操作处理模式，启用异步请求模式能够避免 I/O 操作阻塞消息发布流程，相应的消息时效性也会发生变化：客户端可能已经发出多条消息，但数据桥接还在排队处理先前的消息。
异步请求模式是指数据桥接将对数据执行异步处理，也就是说，客户端可能已经发出了多条消息，但数据桥接还在处理先前排队的消息。启用异步请求模式能够避免 I/O 操作阻塞消息的发布流程，但会影响消息的时效性。

2022-12-26 06:46 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +数据桥接默认启用了异步请求模式以提高数据处理效率，如果您的应用对消息时序有严格要求，请关闭此选项。
为提高数据处理效率，异步请求模式将默认开启，但如果您的应用对消息时序有严格要求，可通过如下命令关闭该模式。

2022-12-26 06:47 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +#### 异步模式配置
关闭异步模式

2022-12-26 06:48 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +批量写入的优点：
批量写入的 可以删掉

2022-12-26 06:48 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +批量写入的缺点：
批量写入的 可以删掉

2022-12-26 06:51 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +- 提高写入效率：通常数据库系统会对批量写入进行优化，比如利用缓存、预编译语句等技术来提高写入效率。因此，批量写入比单条写入更快。
相比单条写入模式，数据库系统通常会对批量写入进行优化，比如缓存、预编译语句等，因此将能提升写入效率。

2022-12-26 06:55 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +- 数据错误可能难以排查：批量写入过程中出现了单条数据错误，该条或整批数据将被丢弃难以排查错误问题。
- 数据错误排查难度较高：如在批量写入过程中出现了单条数据错误，该条或整批数据将被丢弃，因此较难排查错误问题。
- 数据写入时延较长：数据在达到设置的时间或条数之后才会被写入，时延较长。注意：您可以通过下方参数对设置时间或条数进行调整。

2022-12-26 06:57 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +数据桥接默认启用了批量模式，可根据情况关闭此特性。
批量模式默认开启，您可根据业务需要参照如下代码关闭批量模式或调整批量传入的等待时间或消息的累积条数。

2022-12-26 06:58 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +当出现如网络波动、服务宕机等原因导致外部资源不可用时，数据桥接允许将期间产生的消息缓存到内存或磁盘中，待服务恢复时继续发送队列中的消息。
这里好像少了对缓存队列的定义？

2022-12-26 06:59 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +当出现如网络波动、服务宕机等原因导致外部资源不可用时，数据桥接允许将期间产生的消息缓存到内存或磁盘中，待服务恢复时继续发送队列中的消息。
当出现如网络波动、服务宕机等原因导致外部资源不可用时，可通过开启缓存队列将此期间产生的消息缓存到内存或磁盘中，待服务恢复时再继续发送。

2022-12-26 06:59 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +- 是否启用缓存队列。
这里是不是要加上参数名称？

2022-12-26 07:00 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +#### 缓存文件位置
整个缓存文件的位置可以放在第一段

2022-12-26 07:01 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +在诸如 MySQL、PostgreSQL 等 SQL 数据库中，SQL 模板会进行预处理执行，无需显式的指定字段变量。
这里好像也没提到进行 SQL 预处理的优势

2022-12-26 07:08 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridges.md
> +在诸如 MySQL、PostgreSQL 等 SQL 数据库中，SQL 模板会进行预处理执行，无需显式的指定字段变量。
整段调整下，是不是这样：

比如在未开启 SQL 预处理、直接执行 SQL 时，必须通过单引号显式设置 topic 与 payload 为字符类型，qos 为 int 类型，如下所示：

```sql
INSERT INTO msg(topic, qos, payload) VALUES('${topic}', ${qos}, '${payload}');
```

但在开启 SQL 预处理后，数据桥接（还是EMQ？）将自动推导字段类型，无需再额外设置，如下所示：
```sql
INSERT INTO msg(topic, qos, payload) VALUES(${topic}, ${qos}, ${payload});
```

此外，开启 SQL 预处理还可以避免 SQL 注入以提高安全性。


数据桥接（还是EMQ？）将自动推导字段类型 - 这里是谁在自动推导字段类型，我不太确定哈。

2022-12-26 07:08 UTC, LenaLenaPan requested changes
I just finished the data-bridge.md file, please have a look

2022-12-26 07:18 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +我们用一个示例展示如何使用 Dashboard 创建一个简单的 Webhook，桥接到一个 HTTP 服务器。
我们将通过示例来展示如何使用 Dashboard 创建一个简单的 Webhook，并桥接到一个 HTTP 服务器。

2022-12-26 07:19 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +首先我们使用 Python 搭建一个简单的 HTTP 服务。这个 HTTP 服务接收 `POST /` 请求，
首先我们使用 Python 搭建一个简单的 HTTP 服务，用来接收 `POST /` 请求。

2022-12-26 07:24 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +简单打印请求内容后返回 200 OK：
这里的python 命令要不要再解释下？

2022-12-26 07:25 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +将上面的代码保存为 `http_server.py` 文件。然后启动服务：
这里需要告诉用户将文件保存在哪里嘛？

2022-12-26 07:26 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +将上面的代码保存为 `http_server.py` 文件。然后启动服务：
然后启动服务：然后在文件所在的目录，通过命令行运行如下命令：

是不是这个意思？

2022-12-26 07:27 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +现在我们访问 Dashboard，选择左边栏 “数据集成” - “数据桥接”：
咱们的界面词是用括号，还是加粗？建议统一加粗

2022-12-26 07:37 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +现在我们访问 Dashboard，选择左边栏 “数据集成” - “数据桥接”：
界面词统一加粗吧，后面我就不再留类似的 comment了

2022-12-26 07:38 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +在规则的创建页面，填入如下 SQL 语句，其余参数保持默认值：
这个 SQL 语句要不要解释下？

2022-12-26 07:38 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +### 创建 Webhook 并关联到规则
关联到规则，我觉得有点抽象

2022-12-26 07:49 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +MySQL Bridge 可以将客户端消息和事件存储到 MySQL 中，也可以通过事件触发对 MySQL 中的数据执行更新、删除操作实现诸如设备在线状态、上下线历史记录等业务。
MySQL Bridge 可以将客户端消息和事件存储到 MySQL 中，也可以通过事件触发对 MySQL 中数据的更新或删除，从而实现对诸如设备在线状态、上下线历史等的记录。

2022-12-26 07:49 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 先决条件
前置准备

2022-12-26 07:51 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +# MySQL Bridge
这个名字要不要改下，我觉得 Bridge 统一处理为数据桥接，这里的名字或者统一为：
通过 MySQL 进行数据桥接？

2022-12-26 07:51 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-webhook.md
> +我们用一个示例展示如何使用 Dashboard 创建一个简单的 Webhook，桥接到一个 HTTP 服务器。
同上，这篇的名字也建议改为 通过 Webhook 进行数据桥接

2022-12-26 07:52 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 特性
功能特性？

2022-12-26 07:52 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 配置参数
这里需要一句话大体介绍下都有哪些配置参数，可以实现什么

2022-12-26 07:53 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +通过 Docker 安装并启动 MySQL：
对 docker 的版本有要求吗？

2022-12-26 07:54 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +### 创建 MySQL Bridge
这个是界面名称吗？不是的话，不建议这么写，参照公司网页：MySQL 数据桥接

2022-12-26 07:54 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +需要创建两个 MySQL Bridge 分别完成消息存储与事件记录：
同上

2022-12-26 07:54 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
这里的界面词需要统一加粗

2022-12-26 07:55 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +6. 配置 SQL 模板，使用如下 SQL 完成数据插入，此处为预处理 SQL，字段不应当包含引号，SQL 末尾不要带分号 `;`:
预处理 SQL 这里需要连接到 data-bridges 对应的章节

2022-12-26 07:55 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +  请预先在 MySQL 中创建使用以下 SQL 创建存储消息的数据表 `emqx_messages`，该表存储每条消息的发布者客户端 ID、主题、Payload 以及发布时间：
如果是预先操作的话，是不是位置放在前面更好？

2022-12-26 07:56 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
至此您已经完成数据桥接的创建，

您还需要创建一条规则并在规则中选择该数据桥接作为动作：这里的后半句看不懂

2022-12-26 07:56 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +1. 转到 Dashboard 数据集成 -> 规则页面。
界面词需要批量加粗，就不再每个 comment了

2022-12-26 07:57 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +4. 添加动作，在动作下拉框中选择 使用数据桥接转发 选项，选择先前创建好的 MySQL Bridge。
MySQL Bridge 这个名称不建议使用

2022-12-26 07:57 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +至此您已经完成整个创建过程，可以前往 数据集成 -> Flows 页面查看拓扑图，此时应当看到 `t/#` 主题的消息经过名为 `my_rule` 的规则处理，处理结果交由 MySQL Bridge 进行存储。
MySQL Bridge  同上

2022-12-26 08:00 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +需要新建数据桥接与规则，除 SQL 模板与规则 SQL 外大体步骤与[消息存储](#消息存储)一致。
在上面一个章节，我们通过建立到 MySQL 的数据桥接实现了对消息的存储，本节我们将演示如何通过 MySQL 实现对设备上下线的记录。

2022-12-26 08:02 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-mysql.md
> +#### 消息存储
本节我们将创建第一个 MySQL 数据桥接来实现对设备在线状态的存储。

2022-12-26 08:05 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +# Kafka Bridge
这里建议用全名 Apache Kafka，
将数据集成到 Apache Kafka？

2022-12-26 08:07 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +Kafka Bridge 实现了客户端消息和事件与 Apache Kafka(包括 Confluent) 的桥接，能够提供 EMQX 与应用程序之间高性能、高可靠的数据集成，有效降低应用复杂度并提升扩展性。
Kafka Bridge  这个名字我也觉得需要通篇修改下

2022-12-26 08:15 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +Kafka Bridge 实现了客户端消息和事件与 Apache Kafka(包括 Confluent) 的桥接，能够提供 EMQX 与应用程序之间高性能、高可靠的数据集成，有效降低应用复杂度并提升扩展性。
我觉得这段功能说的不是太清楚，Kafka 最大的功能不是实时/近实时吗？

2022-12-26 08:27 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +## 先决条件
前置准备

2022-12-26 08:28 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +- 无论生产者还是消费者模式，均需要预先在 Kafka 创建好对应 Topic。
无论生产者还是消费者模式，均需要预先在 Kafka 创建好对应 Topic。 这句话说的不是太清楚，咱们前面有解释过生产者/消费者模式吗？
用户了解如何在 Kafka 创建对应的topic吗？

2022-12-26 08:28 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +## 特性
每个章节都在列一遍特性的目的是？

2022-12-26 08:29 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +以 macOS 为例，安装并启动 Kafka：
有没有系统版本的要求？

2022-12-26 08:29 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +以 macOS 为例，安装并启动 Kafka：
是不是也要把对应的windows 版本的操作方式写一下？或者给出到kafka官网的链接？

2022-12-26 08:30 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +
这里就是前置准备必须创建 topic 的那一步？那可以不写在前置准备那里

2022-12-26 08:31 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +### 创建 Kafka Bridge
同上，bridge 咱们已经有对应的中文叫法了，不建议再创造新的名词

2022-12-26 08:31 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
界面词需要统一加粗

2022-12-26 08:32 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +目前 Kafka Bridge 仅支持生产者模式。
这个建立放到前置准备那里，不支持消费者模式的话，那在前置准备里提到消费者模式，但是没写明不支持就不太合理。

2022-12-26 08:33 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +## 先决条件
前置准备

2022-12-26 08:33 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +## 特性
同上，咱们每个桥接方式都加上特性的目的是？

2022-12-26 08:33 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 通过 Docker 安装并启动 InfluxDB，详细步骤请参考 [Install InfluxDB](https://docs.influxdata.com/influxdb/v2.5/install/)。
有版本要求或者限制吗？

2022-12-26 08:34 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +### 创建 InfluxDB Bridge
InfluxDB Bridge 同之前所有的xxx bridge，不建议这么叫

2022-12-26 08:34 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
界面词需要统一加粗

2022-12-26 08:34 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
您还需要创建一条规则并在规则中选择该数据桥接作为动作： 这句话在 mysql 有句一模一样的，建议一起调整下

2022-12-26 08:35 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +前往 InfluxDB UI Data Explorer 查看数据是否已经写入 InfluxDB 中。
这里要给个成功写入的截图吗？

2022-12-26 09:58 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +前往 InfluxDB UI Data Explorer 查看数据是否已经写入 InfluxDB 中。
目前 dashboard 一直在变化，可能几个版本后就不适用了要重新截图，工作量有点大

2022-12-26 10:00 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 通过 Docker 安装并启动 InfluxDB，详细步骤请参考 [Install InfluxDB](https://docs.influxdata.com/influxdb/v2.5/install/)。
这里指定了版本了。默认没提及兼容性的话，当前主流版本都是支持的

2022-12-26 10:01 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +## 特性
不同数据桥接支持的特性不一样

2022-12-27 02:21 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +InfluxDB 是一个用于存储和分析时间序列数据的数据库，其强大的数据吞吐能力以及稳定的性能表现使其非常适合物联网领域。InfluxDB Bridge 完整支持 InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise 多种软件类型以及不同版本。
InfluxDB Bridge 完整支持 InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise 多种软件类型以及不同版本。这句话是不是也需要重写下？

EMQX 目前支持通过数据桥接的方式连接不同版本的  InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise。

另外，这里的版本信息是不是也需要解释下？

2022-12-27 02:56 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +2. 访问 [http://localhost:8086.]( http://localhost:8086) 打开 InfluxDB UI，设置用户名、密码、组织名称、Bucket 名称。
访问 [http://localhost:8086. 多了一个.

2022-12-27 03:08 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +InfluxDB 是一个用于存储和分析时间序列数据的数据库，其强大的数据吞吐能力以及稳定的性能表现使其非常适合物联网领域。InfluxDB Bridge 完整支持 InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise 多种软件类型以及不同版本。
多种软件类型以及不同版本。 既然支持主流版本，这里要不就写主流版本吧

2022-12-27 03:09 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +### 创建 InfluxDB Bridge
英文写了 Connect to InfluxDB

2022-12-27 03:56 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
这里的转到 Dashboard，建议连接到dashboard对应的章节

2022-12-27 07:46 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +Kafka Bridge 实现了客户端消息和事件与 Apache Kafka(包括 Confluent) 的桥接，能够提供 EMQX 与应用程序之间高性能、高可靠的数据集成，有效降低应用复杂度并提升扩展性。
能够提供 EMQX 与应用程序之间高性能，这里的应用程序是？

2022-12-27 07:46 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
2. 选择 Token 认证，填入先前设置的组织名称、Bucket 以及生成的 Toekn。 这里的Toekn是错别字

2022-12-27 07:46 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
调优配置（可选）建议用“高级设置”

2022-12-27 07:48 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
调优配置（可选），根据情况配置同步/异步模式，队列与批量等参数，详细请参考[配置配置](#配置参数)。 最后多了一个配置

2022-12-27 07:51 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +前往 InfluxDB UI Data Explorer 查看数据是否已经写入 InfluxDB 中。
转到 Dashboard 数据集成 -> 规则页面。 这里其实在完成桥接的创建之后直接会弹出创建规则的对话框，是不是也应该体现一下？

2022-12-27 07:55 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +前往 InfluxDB UI Data Explorer 查看数据是否已经写入 InfluxDB 中。
请确规则选择出来的字段（SELECT 部分）包含上述数据桥接所需的字段 这个是病句吧

2022-12-27 08:07 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-influxdb.md
> +至此您已经完成数据桥接创建流程，为了指定需要写入的数据，您还需要创建一条规则并在规则中选择该数据桥接作为动作：
您还需要创建一条规则并在规则中选择该数据桥接作为动作：这里我觉得添加为动作是规则的一部分，所以建议省去这部分，

这么写吧：至此您已经完成数据桥接创建流程，我们接下来将继续创建一条规则来指定需要写入的数据。

2022-12-27 08:45 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +   1. MQTT 主题：要桥接的 MQTT 主题，此处填写 `t/#` 表示将匹配此主题的 MQTT 消息转发至 Kafka。您也可以将此项留空，新建规则在规则动作中设置将规则处理结果转发到该数据桥接。
您也可以将此项留空，新建规则在规则动作中设置将规则处理结果转发到该数据桥接。 这句话没看懂

2022-12-27 08:57 UTC, LenaLenaPan commented on zh_CN/data-integration/data-bridge-kafka.md
> +   3. Kafka 消息模板：使用变量构造消息模板，将规则或指定 MQTT 主题的消息转发到 6.2 中的 Kafka 主题中，此处使用 Dashboard 默认即可。
```suggestion
模版用于将规则或指定 MQTT 主题的消息转发到我们之前创建的 Kafka 主题。此处您可以使用默认配置，或通过变量构造消息模板。
```

2022-12-29 07:49 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +InfluxDB 是一个用于存储和分析时间序列数据的数据库，其强大的数据吞吐能力以及稳定的性能表现使其非常适合物联网领域。InfluxDB Bridge 完整支持 InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise 多种软件类型以及不同版本。
```suggestion
InfluxDB 是一个用于存储和分析时间序列数据的数据库，其强大的数据吞吐能力以及稳定的性能表现使其非常适合物联网领域。EMQX 目前支持通过数据桥接的方式连接不同版本的 InfluxDB Cloud、InfluxDB OSS 以及 InfluxDB Enterprise。
```

2022-12-29 07:49 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +2. 访问 [http://localhost:8086.]( http://localhost:8086) 打开 InfluxDB UI，设置用户名、密码、组织名称、Bucket 名称。
```suggestion
2. 访问 [http://localhost:8086]( http://localhost:8086) 打开 InfluxDB UI，设置用户名、密码、组织名称、Bucket 名称。
```

2022-12-29 07:49 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +### 创建 InfluxDB Bridge
```suggestion
### 连接到 InfluxDB
```

2022-12-29 07:49 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
```suggestion
1. 转到 Dashboard **数据集成** -> **数据桥接**页面。
```

2022-12-30 02:49 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +在诸如 MySQL、PostgreSQL 等 SQL 数据库中，SQL 模板会进行预处理执行，无需显式的指定字段变量。
### SQL 预处理

[SQL 预处理](https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html)（Prepared Statements）是一种使用预编译语句执行 SQL 的方法。除了方便维护外，预处理语句还能避免 SQL 注入以提高安全性。

如果某个数据桥接支持 SQL 预处理，则在其 SQL 模板中无需显式的指定字段类型，反之则必须在 SQL 模板中明确数据类型。

比如要将以下数据插入数据库：

```json
{
  "topic": "t/1",
  "qos": 0,
  "payload": "Hello EMQX"
}
```

- topic：消息主题，字符。
- payload：消息内容，字符。
- qos：消息 QoS，整数。

在不支持 SQL 预处理的数据桥接中，必须通过单引号显式设置字段类型，如下所示：

```sql
INSERT INTO msg(topic, qos, payload) VALUES('${topic}', ${qos}, '${payload}');
```

在支持 SQL 预处理的数据桥接中，**必须**使用不带引号的预处理语句：

```sql
INSERT INTO msg(topic, qos, payload) VALUES(${topic}, ${qos}, ${payload});
```

2022-12-30 02:50 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-webhook.md
> +将上面的代码保存为 `http_server.py` 文件。然后启动服务：
不需要指定保存位置，但是执行命令的时候可以告诉切换到文件所在目录

2022-12-30 02:51 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-webhook.md
> +### 创建 Webhook 并关联到规则
已按照 kafka 那边的写法修改

2022-12-30 02:52 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +6. 配置 SQL 模板，使用如下 SQL 完成数据插入，此处为预处理 SQL，字段不应当包含引号，SQL 末尾不要带分号 `;`:
get

2022-12-30 02:52 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-kafka.md
> +Kafka Bridge 实现了客户端消息和事件与 Apache Kafka(包括 Confluent) 的桥接，能够提供 EMQX 与应用程序之间高性能、高可靠的数据集成，有效降低应用复杂度并提升扩展性。
能够提供 EMQX 与企业应用之间高性能、高可靠的数据集成

2022-12-30 02:53 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-kafka.md
> +- 无论生产者还是消费者模式，均需要预先在 Kafka 创建好对应 Topic。
读到这里用户还不理解生产者消费者模式，这里先不提这个概念，仅要求需要预先创建好

2022-12-30 02:55 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +前往 InfluxDB UI Data Explorer 查看数据是否已经写入 InfluxDB 中。
不用单独提，对话框是在界面上是可选项 用户有可能直接跳过了

下面这句已修改

2022-12-30 02:57 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-influxdb.md
> +1. 转到 Dashboard 数据集成 -> 数据桥接页面。
可以不加，Dashboard 是最基本的概念用户应该是知道的？
或者后续再来统一加（我们之前讨论的为每个页面加上 icon）

2022-12-30 02:58 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +  请预先在 MySQL 中创建使用以下 SQL 创建存储消息的数据表 `emqx_messages`，该表存储每条消息的发布者客户端 ID、主题、Payload 以及发布时间：
把 预先 这个词去了，这里出现的顺序还是在 SQL 模板附近比较好，用户能够将 SQL 模板与表结构联系起来。
----------
 请在 MySQL 中使用以下 SQL 创建存储消息的数据表 `emqx_messages`，该表存储每条消息的发布者客户端 ID、主题、Payload 以及发布时间：

2022-12-30 03:01 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 先决条件
下面的内容不算必须去「准备」的动作之类的操作。先决条件/前提条件比较好，如果掌握这个知识点就直接跳过。

这里我看英文里面也还是叫先决条件？

2022-12-30 03:02 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-webhook.md
> +简单打印请求内容后返回 200 OK：
比较简单，懂的不用解释，不懂的解释了也没用（通常用的不是 Python）

2022-12-30 03:03 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +数据桥接借助以下特性以增强易用性、进一步提高数据集成的性能和可靠性，并非所有数据桥接都完全实现了这些特性，具体支持情况请参照各自的说明文档。
不好链接，这里的说明文档指的就是每个数据桥接的文档，有很多个

2022-12-30 03:04 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +<!-- - 命中：
状态跟指标是两个概念，这里你提醒的对 状态 介绍给漏了。已经改为 数据桥接状态与相关指标。

2022-12-30 03:05 UTC, wivwiv commented on zh_CN/data-integration/data-bridges.md
> +#### 异步模式配置
不建议改
- 配置项上不是 enable/disable
- 跟其他功能 xxx 配置 呼应

2022-12-30 03:07 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 配置参数
后续链接

2022-12-30 03:07 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +## 特性
支持特性？表示支持的特性有哪些

2022-12-30 03:07 UTC, wivwiv commented on zh_CN/data-integration/data-bridge-mysql.md
> +通过 Docker 安装并启动 MySQL：
一般不会遇到

2023-01-03 07:13 UTC, merged